import Head from "next/head";
import Image from "next/future/image";

export async function getStaticProps() {
  const res1 = await fetch("https://api.github.com/users/PatMan817");
  const PatrickUserData = await res1.json();
  const res2 = await fetch("https://api.github.com/users/ianzuber221");
  const IanUserData = await res2.json();
  const res3 = await fetch("https://api.github.com/users/taylorthornton");
  const TaylorUserData = await res3.json();
  const userData = [PatrickUserData, IanUserData, TaylorUserData];
  return {
    props: {
      userData,
    },
  };
}

export default function Home({ userData }) {
  return (
    <>
      <Head>
        <title>Fermium&apos;s Product API</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="main">
        <style jsx>{`
        .main {
          text-align: center;
          background-color: white;
          padding: 0px 10px;
        }
        .user-card {
          background-color: whitesmoke;
          padding: 10px 10px 0px 10px;
          box-shadow: 1px 1px 10px 1px black;
          border-radius: 10%;
        }
        .card-container {
          display: flex;
          justify-content: center;
          gap: 2%;
          text-align: center;
          border-radius: 10%;
        }
        `}</style>
        <h1>Welcome to Fermium&apos;s Product API</h1>

        <p>Built using Next.js.</p>

        <div>
          <a href="https://github.com/Fermium-SDC">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Fermium&apos;s APIs.</p>
          </a>
          <h2>Personal Github Profiles</h2>
          <p>See everyone involved in the project.</p>
          <div className="card-container">
            {userData.map((user) => {
              return (
                <a className="user-card" href={user.html_url} key={user.id}>
                  <Image
                    style={{ borderRadius: "10%" }}
                    src={user.avatar_url}
                    alt="github-avatar"
                    width={100}
                    height={100}
                  ></Image>
                  <p>Visit {user.login}&apos;s Github Page</p>
                </a>
              );
            })}
          </div>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
    </>
  );
}
