import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Patrick's Product API</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>
          Welcome to my shopping API
        </h1>

        <p>
          Built using Next.js.
        </p>

        <div>
          <a href="https://github.com/Fermium-SDC">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Fermium's APIs.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
    </>
  )
}
